[workspace]
members = ["src-tauri", "src"]
resolver = "2"

[workspace.package]
version = "0.1.1"
edition = "2021"

[workspace.dependencies]
# Shared dependencies
anyhow = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
